spring:
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/template/
    suffix: .html
    cache: false #关闭缓存
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 101.132.168.238
    port: 6379
    password: lynn123.
    timeout: 1000
  datasource:
    url: jdbc:mysql://101.132.168.238:3306/record?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username : root
    password: lynn123.

logging.level.org.springframework.boot.autoconfigure: ERROR

server:
  port: 80

