spring:
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false #关闭缓存
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 101.132.168.238
    port: 6379
    password: lynn123.
    timeout: 1000

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.132.168.238:3306/record?useUnicode=true&characterEncoding=utf-8
    username : root
    password: lynn123.


server:
  port: 80

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations:
